baseURL = 'https://nudcacode.github.io/nudca.github.io/'
languageCode = 'en-us'
title = 'NuDCA'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = ['blue']
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

