baseURL = 'https://qiuhongchen.github.io/nudca.github.io/'
languageCode = 'en-us'
title = 'NuDCA'
theme = 'hugo-theme-relearn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
