baseURL = 'https://nudcacode.github.io/nudca-main/'
languageCode = 'en-us'
title = 'NuDCA'
theme = 'hugo-theme-relearn'  

[params]
  linkTitle = 'NuDCA'
  themeVariant = ['blue']
  math = true

  collapsibleMenu = true
  alwaysopen = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


[menu]
  [[menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-github"></i> '
    name = 'ENDF-B-VIII.1'
    url = 'https://www-nds.iaea.org/public/download-endf/ENDF-B-VIII.1/decay/'
    weight = 2

  [[menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-github"></i> '
    name = 'ENDFtk'
    url = 'https://github.com/njoy/ENDFtk'
    weight = 2


